import { contextBridge, ipcRenderer } from 'electron';

contextBridge.exposeInMainWorld('electronAPI', {
    window: {
        minimize: () => ipcRenderer.invoke('window:minimize'),
        maximize: () => ipcRenderer.invoke('window:maximize'),
        close: () => ipcRenderer.invoke('window:close'),
        isMaximized: () => ipcRenderer.invoke('window:isMaximized'),
        onMaximizeChange: cb => { const h = (_e, v) => cb(v); ipcRenderer.on('window:maximizeChange', h); return () => ipcRenderer.removeListener('window:maximizeChange', h); },
        openExternal: url => ipcRenderer.invoke('shell:openExternal', url),
        openPath: p => ipcRenderer.invoke('shell:openPath', p),
    },
    server: {
        onUrl: cb => { const h = (_e, u) => cb(u); ipcRenderer.on('server:url', h); return () => ipcRenderer.removeListener('server:url', h); },
        onError: cb => { const h = (_e, m) => cb(m); ipcRenderer.on('server:error', h); return () => ipcRenderer.removeListener('server:error', h); },
        onSetupStarted: cb => { const h = () => cb(); ipcRenderer.on('setup:started', h); return () => ipcRenderer.removeListener('setup:started', h); },
        restart: () => ipcRenderer.invoke('server:restart'),
        getUrl: () => ipcRenderer.invoke('server:getUrl'),
    },
    terminal: {
        onOutput: cb => { const h = (_e, t) => cb(t); ipcRenderer.on('terminal:output', h); return () => ipcRenderer.removeListener('terminal:output', h); },
        getHistory: () => ipcRenderer.invoke('terminal:getHistory'),
        exec: cmd => ipcRenderer.invoke('terminal:exec', cmd),
    },
    settings: {
        get: () => ipcRenderer.invoke('settings:get'),
        save: obj => ipcRenderer.invoke('settings:save', obj),
        getServerPath: () => ipcRenderer.invoke('settings:getServerPath'),
        setServerPath: p => ipcRenderer.invoke('settings:setServerPath', p),
        getDataRoot: () => ipcRenderer.invoke('settings:getDataRoot'),
    },
    app: { getVersion: () => ipcRenderer.invoke('app:getVersion'), getShellVersion: () => ipcRenderer.invoke('app:getShellVersion'), getChangelog: () => ipcRenderer.invoke('app:getChangelog'), contextMenu: opts => ipcRenderer.send('app:contextMenu', opts), onCtxCmd: cb => { const h = (_e, cmd) => cb(cmd); ipcRenderer.on('ctx:cmd', h); return () => ipcRenderer.removeListener('ctx:cmd', h); }, onShellAction: cb => { const h = (_e, a) => cb(a); ipcRenderer.on('shell:action', h); return () => ipcRenderer.removeListener('shell:action', h); } },
    update: {
        check: () => ipcRenderer.invoke('update:check'),
        updateSillyTavern: () => ipcRenderer.invoke('update:sillytavern'),
    },
    shellUpdate: {
        check: () => ipcRenderer.invoke('shell-update:check'),
        download: () => ipcRenderer.invoke('shell-update:download'),
        install: () => ipcRenderer.invoke('shell-update:install'),
        onProgress: cb => { const h = (_e, p) => cb(p); ipcRenderer.on('shell-update:progress', h); return () => ipcRenderer.removeListener('shell-update:progress', h); },
        onDownloaded: cb => { const h = () => cb(); ipcRenderer.on('shell-update:downloaded', h); return () => ipcRenderer.removeListener('shell-update:downloaded', h); },
        onError: cb => { const h = (_e, e) => cb(e); ipcRenderer.on('shell-update:error', h); return () => ipcRenderer.removeListener('shell-update:error', h); },
    },
    bench: {
        status: () => ipcRenderer.invoke('bench:status'),
        benchmark: () => ipcRenderer.invoke('bench:benchmark'),
        reset: () => ipcRenderer.invoke('bench:reset'),
    },
    tools: {
        // A 档
        backupNow: () => ipcRenderer.invoke('tools:backupNow'),
        backupList: () => ipcRenderer.invoke('tools:backupList'),
        backupConfig: () => ipcRenderer.invoke('tools:backupConfig'),
        backupSave: cfg => ipcRenderer.invoke('tools:backupSave', cfg),
        rollbackList: () => ipcRenderer.invoke('tools:rollbackList'),
        rollbackInstall: v => ipcRenderer.invoke('tools:rollbackInstall', v),
        autostartGet: () => ipcRenderer.invoke('tools:autostartGet'),
        autostartSet: on => ipcRenderer.invoke('tools:autostartSet', on),
        immerseSet: on => ipcRenderer.invoke('tools:immerseSet', on),
        nightGet: () => ipcRenderer.invoke('tools:nightGet'),
        nightSave: cfg => ipcRenderer.invoke('tools:nightSave', cfg),
        pinGet: () => ipcRenderer.invoke('tools:pinGet'),
        pinSet: code => ipcRenderer.invoke('tools:pinSet', code),
        pinVerify: code => ipcRenderer.invoke('tools:pinVerify', code),
        portablePick: () => ipcRenderer.invoke('tools:portablePick'),
        onNight: cb => { const h = (_e, v) => cb(v); ipcRenderer.on('ui:night', h); return () => ipcRenderer.removeListener('ui:night', h); },
        // B 档
        searchChats: kw => ipcRenderer.invoke('tools:searchChats', kw),
        summarizeChat: () => ipcRenderer.invoke('tools:summarizeChat'),
        listCharacters: () => ipcRenderer.invoke('tools:listCharacters'),
        exportCharacters: () => ipcRenderer.invoke('tools:exportCharacters'),
        chatStats: () => ipcRenderer.invoke('tools:chatStats'),
        // C 档
        envCheck: () => ipcRenderer.invoke('tools:envCheck'),
        ollamaModels: () => ipcRenderer.invoke('tools:ollamaModels'),
        ollamaPs: () => ipcRenderer.invoke('tools:ollamaPs'),
        ollamaAction: (a, m) => ipcRenderer.invoke('tools:ollamaAction', a, m),
        gpuStats: () => ipcRenderer.invoke('tools:gpuStats'),
        clashCheck: () => ipcRenderer.invoke('tools:clashCheck'),
        // D 档
        chatOpen: () => ipcRenderer.invoke('tools:chatOpen'),
        chatModel: () => ipcRenderer.invoke('tools:chatModel'),
        chatSend: t => ipcRenderer.invoke('tools:chatSend', t),
        chatClear: () => ipcRenderer.invoke('tools:chatClear'),
        draftGenerate: (p, n) => ipcRenderer.invoke('tools:draftGenerate', p, n),
    },
});
