import { contextBridge, ipcRenderer } from 'electron';

contextBridge.exposeInMainWorld('electronAPI', {
    window: {
        minimize: () => ipcRenderer.invoke('window:minimize'),
        maximize: () => ipcRenderer.invoke('window:maximize'),
        close: () => ipcRenderer.invoke('window:close'),
        isMaximized: () => ipcRenderer.invoke('window:isMaximized'),
        onMaximizeChange: cb => { const h = (_e, v) => cb(v); ipcRenderer.on('window:maximizeChange', h); return () => ipcRenderer.removeListener('window:maximizeChange', h); },
        openExternal: url => ipcRenderer.invoke('shell:openExternal', url),
        openPath: p => ipcRenderer.invoke('shell:openPath', p),
        pickDirectory: () => ipcRenderer.invoke('shell:pickDirectory'),
    },
    shellAuth: {
        onRequired: cb => { const h = (_e, info) => cb(info); ipcRenderer.on('shell:auth-required', h); return () => ipcRenderer.removeListener('shell:auth-required', h); },
        respond: payload => ipcRenderer.invoke('shell:auth-respond', payload),
        retry: payload => ipcRenderer.invoke('shell:auth-retry', payload),
    },
    zeroTier: {
        status: () => ipcRenderer.invoke('tools:ztStatus'),
        join: id => ipcRenderer.invoke('tools:ztJoin', id),
        leave: id => ipcRenderer.invoke('tools:ztLeave', id),
    },
    server: {
        onUrl: cb => { const h = (_e, u) => cb(u); ipcRenderer.on('server:url', h); return () => ipcRenderer.removeListener('server:url', h); },
        onError: cb => { const h = (_e, m) => cb(m); ipcRenderer.on('server:error', h); return () => ipcRenderer.removeListener('server:error', h); },
        onSetupStarted: cb => { const h = () => cb(); ipcRenderer.on('setup:started', h); return () => ipcRenderer.removeListener('setup:started', h); },
        restart: () => ipcRenderer.invoke('server:restart'),
        getUrl: () => ipcRenderer.invoke('server:getUrl'),
    },
    terminal: {
        onOutput: cb => { const h = (_e, t) => cb(t); ipcRenderer.on('terminal:output', h); return () => ipcRenderer.removeListener('terminal:output', h); },
        getHistory: () => ipcRenderer.invoke('terminal:getHistory'),
        exec: cmd => ipcRenderer.invoke('terminal:exec', cmd),
        exportLog: () => ipcRenderer.invoke('terminal:export'),
    },
    settings: {
        get: () => ipcRenderer.invoke('settings:get'),
        save: obj => ipcRenderer.invoke('settings:save', obj),
        getServerPath: () => ipcRenderer.invoke('settings:getServerPath'),
        setServerPath: p => ipcRenderer.invoke('settings:setServerPath', p),
        getDataRoot: () => ipcRenderer.invoke('settings:getDataRoot'),
    },
    app: { getVersion: () => ipcRenderer.invoke('app:getVersion'), getShellVersion: () => ipcRenderer.invoke('app:getShellVersion'), getChangelog: () => ipcRenderer.invoke('app:getChangelog'), contextMenu: opts => ipcRenderer.send('app:contextMenu', opts), onCtxCmd: cb => { const h = (_e, cmd) => cb(cmd); ipcRenderer.on('ctx:cmd', h); return () => ipcRenderer.removeListener('ctx:cmd', h); }, onShellAction: cb => { const h = (_e, a) => cb(a); ipcRenderer.on('shell:action', h); return () => ipcRenderer.removeListener('shell:action', h); } },
    update: {
        check: () => ipcRenderer.invoke('update:check'),
        updateSillyTavern: () => ipcRenderer.invoke('update:sillytavern'),
    },
    shellUpdate: {
        check: () => ipcRenderer.invoke('shell-update:check'),
        download: () => ipcRenderer.invoke('shell-update:download'),
        install: () => ipcRenderer.invoke('shell-update:install'),
        onProgress: cb => { const h = (_e, p) => cb(p); ipcRenderer.on('shell-update:progress', h); return () => ipcRenderer.removeListener('shell-update:progress', h); },
        onDownloaded: cb => { const h = () => cb(); ipcRenderer.on('shell-update:downloaded', h); return () => ipcRenderer.removeListener('shell-update:downloaded', h); },
        onError: cb => { const h = (_e, e) => cb(e); ipcRenderer.on('shell-update:error', h); return () => ipcRenderer.removeListener('shell-update:error', h); },
    },
    tools: {
        // A 档
        backupNow: () => ipcRenderer.invoke('tools:backupNow'),
        backupList: () => ipcRenderer.invoke('tools:backupList'),
        backupRestore: name => ipcRenderer.invoke('tools:backupRestore', name),
        backupConfig: () => ipcRenderer.invoke('tools:backupConfig'),
        backupSave: cfg => ipcRenderer.invoke('tools:backupSave', cfg),
        rollbackList: () => ipcRenderer.invoke('tools:rollbackList'),
        rollbackInstall: v => ipcRenderer.invoke('tools:rollbackInstall', v),
        autostartGet: () => ipcRenderer.invoke('tools:autostartGet'),
        autostartSet: on => ipcRenderer.invoke('tools:autostartSet', on),
        immerseSet: on => ipcRenderer.invoke('tools:immerseSet', on),
        nightGet: () => ipcRenderer.invoke('tools:nightGet'),
        nightSave: cfg => ipcRenderer.invoke('tools:nightSave', cfg),
        pinGet: () => ipcRenderer.invoke('tools:pinGet'),
        pinSet: code => ipcRenderer.invoke('tools:pinSet', code),
        pinVerify: code => ipcRenderer.invoke('tools:pinVerify', code),
        portablePick: () => ipcRenderer.invoke('tools:portablePick'),
        lanConfig: () => ipcRenderer.invoke('tools:lanConfig'),
        lanSave: cfg => ipcRenderer.invoke('tools:lanSave', cfg),
        lanIps: () => ipcRenderer.invoke('tools:lanIps'),
        uiGet: () => ipcRenderer.invoke('tools:uiGet'),
        uiSet: (k, v) => ipcRenderer.invoke('tools:uiSet', k, v),
        crashCheck: () => ipcRenderer.invoke('tools:crashCheck'),
        crashMark: () => ipcRenderer.invoke('tools:crashMark'),
        onMini: cb => { const h = (_e, v) => cb(v); ipcRenderer.on('mini:state', h); return () => ipcRenderer.removeListener('mini:state', h); },
        onNight: cb => { const h = (_e, v) => cb(v); ipcRenderer.on('ui:night', h); return () => ipcRenderer.removeListener('ui:night', h); },
        // B 档
        searchChats: kw => ipcRenderer.invoke('tools:searchChats', kw),
        summarizeChat: () => ipcRenderer.invoke('tools:summarizeChat'),
        listCharacters: () => ipcRenderer.invoke('tools:listCharacters'),
        exportCharacters: () => ipcRenderer.invoke('tools:exportCharacters'),
        chatStats: () => ipcRenderer.invoke('tools:chatStats'),
        integrityCheck: () => ipcRenderer.invoke('tools:integrityCheck'),
        exportChatHtml: () => ipcRenderer.invoke('tools:exportChatHtml'),
        cardPreview: n => ipcRenderer.invoke('tools:cardPreview', n),
        worldBooks: () => ipcRenderer.invoke('tools:worldBooks'),
        ragSearch: q => ipcRenderer.invoke('tools:ragSearch', q),
        // C 档
        envCheck: () => ipcRenderer.invoke('tools:envCheck'),
        healthCheck: () => ipcRenderer.invoke('tools:healthCheck'),
        qrcode: text => ipcRenderer.invoke('tools:qrcode', text),
        modelService: () => ipcRenderer.invoke('tools:modelService'),
        ollamaModels: () => ipcRenderer.invoke('tools:ollamaModels'),
        ollamaPs: () => ipcRenderer.invoke('tools:ollamaPs'),
        ollamaAction: (a, m) => ipcRenderer.invoke('tools:ollamaAction', a, m),
        gpuStats: () => ipcRenderer.invoke('tools:gpuStats'),
        clashCheck: () => ipcRenderer.invoke('tools:clashCheck'),
        // D 档
        chatOpen: () => ipcRenderer.invoke('tools:chatOpen'),
        chatModel: () => ipcRenderer.invoke('tools:chatModel'),
        chatSend: (t, sid) => ipcRenderer.invoke('tools:chatSend', t, sid),
        chatClear: sid => ipcRenderer.invoke('tools:chatClear', sid),
        chatSessions: () => ipcRenderer.invoke('tools:chatSessions'),
        chatLoad: sid => ipcRenderer.invoke('tools:chatLoad', sid),
        chatNew: () => ipcRenderer.invoke('tools:chatNew'),
        draftGenerate: (p, n) => ipcRenderer.invoke('tools:draftGenerate', p, n),
        // 公网隧道 (Cloudflare)
        tunnelStart: () => ipcRenderer.invoke('tools:tunnelStart'),
        tunnelStop: () => ipcRenderer.invoke('tools:tunnelStop'),
        tunnelStatus: () => ipcRenderer.invoke('tools:tunnelStatus'),
        tunnelOnState: cb => { const h = (_e, v) => cb(v); ipcRenderer.on('tunnel:state', h); return () => ipcRenderer.removeListener('tunnel:state', h); },
    },
    // D 档（chat.html 独立窗口使用顶层扁平 API）
    chatOpen: () => ipcRenderer.invoke('tools:chatOpen'),
    chatModel: () => ipcRenderer.invoke('tools:chatModel'),
    chatSend: (t, sid) => ipcRenderer.invoke('tools:chatSend', t, sid),
    chatClear: sid => ipcRenderer.invoke('tools:chatClear', sid),
    chatSessions: () => ipcRenderer.invoke('tools:chatSessions'),
    chatLoad: sid => ipcRenderer.invoke('tools:chatLoad', sid),
    chatNew: () => ipcRenderer.invoke('tools:chatNew'),
    draftGenerate: (p, n) => ipcRenderer.invoke('tools:draftGenerate', p, n),
});
